###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM  =   mpicomm
EOS      =   eos_idealgas
HYDRO    =   hydro
DENSITY  =   density
ENTROPY  = noentropy
MAGNETIC =   magnetic
GRAVITY  = nogravity
FORCING  = noforcing
FOURIER  =   fourier_fftpack
POWER    =   power_spectrum
SPECIAL  =   special/chiral_mhd special/gravitational_waves_hTXk
#REAL_PRECISION=double
